### PR TITLE
Starting Board

### PR DESCRIPTION
**Pull request by MircaSalvatorul**

### CODE REVIEW

**Comment by MircaSalvatorul** [comment]
image_2024-10-09_222308428

**Review by AndreeaMagda — CHANGES_REQUESTED** [review]
When i run the project i receive this err 
image

**Comment by MircaSalvatorul** [comment]
Since used colors are not saved by GitHub. here is what i am using:
- Main Camera: Background: A5B68D
- Tile: Script: Base Color: FFF7D1
- Tile: Script: Offset Color: FFD09B

**Review by AndreeaMagda — APPROVED** [review]
All good now!!

**Pull request merged**
